### ISSUE TITLE
Week 13 (Project Plan)

### ISSUE THREAD

**Issue by jameshunter12** [CubNavarro/Tri2GroupFastpages#2]
- [x] Introduce Calling and Developing Procedures
- [x] Create a game to demonstrate
- [x] Make it interactive
- [x] Possibly a quiz for homework
